org: phplegencysquad
app: aws-node-http-api
service: aws-node-http-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  deploymentMethod: direct

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  bye:
    handler: handler.bye
    events:
      - httpApi:
          path: /bye
          method: get
